### ISSUE TITLE
Wrong coverage on t-shirt

### ISSUE THREAD

**Issue by The-Compiler** [pytest-dev/pytest-design#3]
I noticed this just now on the final confirmation before printing: The coverage percentages on the shirt are wrong.

I could just ignore it and go on, but then I can't sleep at night anymore :laughing: 

If we want 30% coverage for the arms (which sounds sensible), that should be 165 missing statements. The total coverage would then raise to 72%.

I tried fixing this myself, but even with Adobe Source Code Pro installed I get a fallback font... So can you do please, @kvas-it? This is blocking the printing of the shirts, so if we could have an updated version until Monday that'd be great.

**Comment by kvas-it** [comment]
You're right. Not sure how this happened, I'm pretty sure I tried to calculate the coverage to make it correct, but obviously that didn't quite work. Yeah, I'll fix it by Monday and push the new version.

**Comment by kvas-it** [comment]
This seems to be fixed (let me know if there's something that I missed).

However, I've noticed that the original version of T-shirt design in .svg has wrong alignment of the coverage numbers and headers. This makes it impossible for anyone but me to edit it. I'm not sure why this happens (the original is an .idraw file that has it right), I'll try to fix that too.

**Comment by The-Compiler** [comment]
LGTM now, sending the new `test_tshirt_curves_nobg.svg` to the company printing them. Thank you! :+1:
