### ISSUE TITLE
Corrupt file?

### ISSUE THREAD

**Issue by The-Compiler** [pytest-dev/pytest-design#4]
I sent the updated `test_tshirt_curves_nobg.svg` to the printer, and it imported to them in Corel Draw and Adobe Illustrator like this:

![abzug](https://cloud.githubusercontent.com/assets/625793/18660861/104dcbb6-7f13-11e6-9294-7782e5f0b4dd.png)

(with the bottom part missing...)

They also tried with Inkscape and that apparently refuses to open the file entirely.

It worked fine for me, so I could export it to a PDF and that worked fine - but do you have an idea what happened there?

**Comment by kvas-it** [comment]
Opening the file in browsers (Chrome, Firefox and Safari) seems to work and it's displayed correctly (also when done via [github interface](https://github.com/pytest-dev/pytest-design/blob/master/test_tshirt_curves_nobg.svg)). Opening it in Inkscape (on Mac OS X) also worked fine. Could it be that the file was damaged during uploading?

**Comment by The-Compiler** [comment]
The file I've sent is the same as in the repo - but I sent it as a mail attachment, so maybe something went wrong on their side (or in their ticket system)... Closing this for now. Glad they have a final preview before printing! :laughing:
